### PR TITLE
Fix pickup completion check

### LINKED ISSUE #304: Unable to Finish Pickup Event after end
This is the error message shown when trying to finish a pickup event once the end time has passed. Can we modify the restriction such that the pickup event can be ended any time the day of the pickup event?

Screen_Shot_2022-04-11_at_5 02 41_PM

### PR DESCRIPTION
**Pull request by michl1001**
Closes #304.

Adds tests to ensure working functionality

### CODE REVIEW

**Comment by shravanhariharan2** [comment]
Instead of checking if the pickup is in the present or past, can we just check if its in the future? i.e. if a pickup event's start time is in the future, don't allow the event to be completed.

**Comment by shravanhariharan2** [comment]
Also, can we rename this PR to match the naming convention from other PRs? (e.g. present tense declarative, like "Implement the ACM stock market"

File: services/MerchStoreService.ts [hunk 1]
```diff
@@ -884,6 +884,14 @@ export default class MerchStoreService {
...
   }
 
+  private static isFuturePickupEvent(pickupEvent: OrderPickupEventModel): boolean {
+    return moment().isBefore(moment(pickupEvent.start), 'day');
+  }
+
+  private static isPastPickupEvent(pickupEvent: OrderPickupEventModel): boolean {
+    return moment().isAfter(moment(pickupEvent.start), 'day');
+  }
+
```
Comment (shravanhariharan2) [inline services/MerchStoreService.ts:894]: If we specify the granularity `'day'`, then we are only comparing the days of the two rather than the actual times. So if the pickup event is at 4pm and it's 2pm right now, then `isFuturePickupEvent` would be false because today is not before today. So we don't want to specify the granularity of `day`. Can we add a test to check that we can't complete a pickup event on the same day if the time is before the pickup event?

also nit: I don't think isPastPickupEvent is being used so let's remove it

**Review by shravanhariharan2 — CHANGES_REQUESTED** [review]

**Review by shravanhariharan2 — APPROVED** [review]
